<!DOCTYPE html>
<html lang="de-de">
  <head>
    <?php include('preface.inc') ?>
    <title>Tomaten und Kartoffeln</title>
  </head>
  <body>
    <div class="grid">
      <header>
          To&shy;ma&shy;ten und Kar&shy;tof&shy;feln
      </header>
      <aside class="sidebar-left">
        <span>
          <a href="../tomato.php">Tomaten</a><br>
          <a href="../potato.php">Kartoffeln</a><br>
          <a href="../special.php">Sonderangebote</a><br>
        </span>
      </aside>
      <main>
